//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class АудиотекаEntities1 : DbContext
    {
        private static АудиотекаEntities1 _context;
        public АудиотекаEntities1()
            : base("name=АудиотекаEntities1")
        {
        }

        public static АудиотекаEntities1 GetContext()
        {
            if (_context == null)
                _context = new АудиотекаEntities1();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Альбомы> Альбомы { get; set; }
        public virtual DbSet<Аудиофайлы> Аудиофайлы { get; set; }
        public virtual DbSet<Жанры> Жанры { get; set; }
        public virtual DbSet<Исполнители> Исполнители { get; set; }
        public virtual DbSet<Языки> Языки { get; set; }
    }
}
